# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessagingExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'

  # Pods for MessagingExample
pod 'Firebase/Messaging'

  target 'MessagingExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MessagingExampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessagingExampleSwift

end
